spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/object_storage_app
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

minio:
  url: http://localhost:9000
  access-key: minio-access-key
  secret-key: minio-secret-key
  bucket: object-storage-app

  # DB migrations settings
  liquibase:
    change-log: db/changelog/changelog.yaml
    contexts: main, test
    liquibase-schema: public
    user: postgres
    password: postgres
